# Generated by Django 5.1.5 on 2025-01-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Заголовок'),
        ),
    ]
