# Generated by Django 5.1.5 on 2025-01-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_favoritenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header/')),
            ],
        ),
    ]
