# Generated by Django 5.1.5 on 2025-01-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_headerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderImage',
        ),
    ]
