# Generated by Django 5.1.5 on 2025-01-30 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_headerimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoritenews',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique_favorite_news'),
        ),
    ]
